/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { CreateServiceEndpointArgs } from "./CreateServiceEndpointArgs";
import { UpdateServiceEndpointArgs } from "./UpdateServiceEndpointArgs";
import { DeleteServiceEndpointArgs } from "./DeleteServiceEndpointArgs";
import { ServiceEndpointFindManyArgs } from "./ServiceEndpointFindManyArgs";
import { ServiceEndpointFindUniqueArgs } from "./ServiceEndpointFindUniqueArgs";
import { ServiceEndpoint } from "./ServiceEndpoint";
import { ServiceEndpointService } from "../serviceEndpoint.service";

@graphql.Resolver(() => ServiceEndpoint)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class ServiceEndpointResolverBase {
  constructor(
    protected readonly service: ServiceEndpointService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "ServiceEndpoint",
    action: "read",
    possession: "any",
  })
  async _serviceEndpointsMeta(
    @graphql.Args() args: ServiceEndpointFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [ServiceEndpoint])
  @nestAccessControl.UseRoles({
    resource: "ServiceEndpoint",
    action: "read",
    possession: "any",
  })
  async serviceEndpoints(
    @graphql.Args() args: ServiceEndpointFindManyArgs
  ): Promise<ServiceEndpoint[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => ServiceEndpoint, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "ServiceEndpoint",
    action: "read",
    possession: "own",
  })
  async serviceEndpoint(
    @graphql.Args() args: ServiceEndpointFindUniqueArgs
  ): Promise<ServiceEndpoint | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => ServiceEndpoint)
  @nestAccessControl.UseRoles({
    resource: "ServiceEndpoint",
    action: "create",
    possession: "any",
  })
  async createServiceEndpoint(
    @graphql.Args() args: CreateServiceEndpointArgs
  ): Promise<ServiceEndpoint> {
    return await this.service.create({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => ServiceEndpoint)
  @nestAccessControl.UseRoles({
    resource: "ServiceEndpoint",
    action: "update",
    possession: "any",
  })
  async updateServiceEndpoint(
    @graphql.Args() args: UpdateServiceEndpointArgs
  ): Promise<ServiceEndpoint | null> {
    try {
      return await this.service.update({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => ServiceEndpoint)
  @nestAccessControl.UseRoles({
    resource: "ServiceEndpoint",
    action: "delete",
    possession: "any",
  })
  async deleteServiceEndpoint(
    @graphql.Args() args: DeleteServiceEndpointArgs
  ): Promise<ServiceEndpoint | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
